version: '3.8'
services:
  db:
    image: postgres:12.22
    environment:
      POSTGRES_DB: kevaluaciondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/kevaluaciondb
    ports:
      - "8080:8080"
volumes:
  db_data: